config/routes.rb
Rails.application.routes.draw do
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
  root 'welcome#quiz'
  get 'index', to: 'welcome#top'
  get 'quiz', to: 'welcome#quiz'
  get 'topic', to: 'welcome#topic'
  get 'import', to: 'welcome#import'
  post 'import', to: 'welcome#import_csv'
  get 'easy', to: 'welcome#quiz'
  get 'medium', to: 'welcome#quiz'
  get 'hard', to: 'welcome#quiz'
  get 'veryhard', to: 'welcome#quiz'
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/option.rb
class Option < ApplicationRecord
	belongs_to :question
end

app/models/question.rb
class Question < ApplicationRecord
	has_many :options, dependent: :delete_all

	def level_text
		case level.to_i
		when 2
			return '中級'
		when 3
			return '上級'
		when 4
			return '最上級'
		else
			return '初級'
		end
	end
end

app/models/topic.rb
class Topic < ApplicationRecord
end

app/models/work.rb
class Work < ApplicationRecord
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
end

app/controllers/welcome_controller.rb
class WelcomeController < ApplicationController
	before_action :check_mobile
	require 'csv'
	def top
		@topics = Topic.all
	end
	def topic
	  require 'rss'
	  require 'open-uri'
	  Topic.destroy_all
	  rss_results = []
	  rss = RSS::Parser.parse(open('https://eiken-anime.jp/?feed=rss2&cat=72').read, false).items[0..5]
	  rss.each do |result|
	    Topic.create(title: result.title, date: result.pubDate, link: result.link, description: result.description)
	  end

	  @topics = Topic.all
	end

	def quiz
		Rails.logger.info request.url.split('/').last
		level = 1
		case request.url.split('/').last
		when 'medium'
			level = 2
		when 'hard'
			level = 3
		when 'veryhard'
			level = 4
		end

		flag = false
		if session[:current_cnt].nil?
			flag = true
		else
			current_id = session[:quiz_ids][session[:current_cnt]]
			quiz = Question.find(current_id)
			flag = true if quiz.level != level

			session[:current_cnt] += 1 if params[:option_id].present?
		end

		if flag
			session[:quiz_ids] = Question.where(level: level).order("RANDOM()").limit(10).collect(&:id)
			Rails.logger.info "#{session[:quiz_ids]}"
			session[:current_cnt] = 0
			session[:mark] = 0
		end
		Rails.logger.info "#{session[:current_cnt]}=========="

		if session[:current_cnt] == 10
			@mark = session[:mark]
			reset_session
		else
			prev_id = session[:quiz_ids][session[:current_cnt] - 1]
			current_id = session[:quiz_ids][session[:current_cnt]]
			Rails.logger.info "#{session[:current_cnt]}________#{prev_id}______#{current_id}______"
			@quiz = Question.find(current_id)
			if params[:option_id].present?
				@option_id = true
				@prev_quiz = Question.find(prev_id)
				correct_option = @prev_quiz.options[@prev_quiz.correct.to_i - 1]
				@answer = correct_option.value
				@correct = false
				if correct_option.id == params[:option_id].to_i
					session[:mark] += 10 
					@correct = true
				end
			else
				Rails.logger.info "#{prev_id}______#{current_id}______"
			end
		end
	end

	def import_csv
		
		Rails.logger.info params[:level]
		level = params[:level].to_i
		Question.where(level: level).delete_all
			
		
		file = File.open(params[:file].path, 'r')
		content = file.read.force_encoding('UTF-8')
		content.gsub!("\xEF\xBB\xBF".force_encoding('UTF-8'), '')
		csv = CSV.parse(content, headers: false)
		csv.each do |quiz|
			question = Question.create(work: quiz[0], quiz: quiz[1], correct: quiz[6], description: quiz[7], level: params[:level].to_i)
			question.options.create(value: quiz[2])
			question.options.create(value: quiz[3])
			question.options.create(value: quiz[4])
			question.options.create(value: quiz[5])
		end
	end

	def check_mobile
		Rails.logger.info request.smart_phone?
		Rails.logger.info request.mobile?
		Rails.logger.info request.tablet?
		if request.smart_phone? || request.mobile? || request.tablet?
			@is_mobile = true
		else
			@is_mobile = false
		end
		Rails.logger.info @is_mobile
	end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/welcome_helper.rb
module WelcomeHelper
end

app/views/layouts/application.html.slim
doctype html
html
  head
    meta content=("text/html; charset=UTF-8") http-equiv="Content-Type" /
    title クイズ
    = csrf_meta_tags
    = csp_meta_tag
    = stylesheet_link_tag    'application', media: 'all'
    = javascript_include_tag 'application'

  - body_id = 'content'
  - if action_name == 'top'
    - body_id = 'pagetop'

  body id="#{body_id}"
    = yield

app/views/welcome/import.html.slim
div style="text-align: center;"
	= form_tag import_path, multipart: true do
		div style="display: flex; padding: 50px; justify-content: center;"
			= select('', :level, options_for_select([['初級', 1], ['中級', 2], ['上級', 3], ['最上級', 4],]), {}, {style: "margin-right: 20px;"})
			= file_field_tag :file
			= submit_tag "インポート"

app/views/welcome/quiz.html.slim
div
  / .pc
  /   header
  /     .top-menu
  /       div
  /         = link_to image_tag("bt_home_pc.png"), root_path
  /       div
  /         = link_to image_tag("bt_01.png"), topic_url
  /       div
  /         = link_to image_tag("bt_02.png"), root_path
  /       div
  /         = link_to image_tag("bt_03.png"), quiz_url
  /       div
  /         = link_to image_tag("bt_04.png"), root_path
  /       div
  /         = link_to image_tag("bt_05.png"), root_path
  /     p.tag-name
  /       | クイズ
  / .sp
  /   .header
  /     = link_to image_tag("bt_home.png"), root_path
  /     = link_to image_tag("bt_01.png"), topic_url
  /     = link_to image_tag("bt_02.png"), root_path
  /     = link_to image_tag("bt_03.png"), quiz_url
  /     = link_to image_tag("bt_04.png"), root_path
  /     = link_to image_tag("bt_05.png"), root_path
  article
    - unless @mark.nil?
      .mark
        div
          - mark_img_name = "#{@mark}.jpg"
          - mark_img_url = image_url(mark_img_name)
          = image_tag(mark_img_url)
          .prettySocial data-description="クイズテスト：#{@mark}点" data-media="#{mark_img_url}" data-type="twitter" data-url="#{request.original_url}" 
            = image_tag(image_url("share.png"))

        p.evalution もう少しエイケンのことを知ってくれるとうれしいな！
      
    - else
      - unless @option_id.nil?
        .answer
          div
            = image_tag( @correct ? "a_right_title.jpg" : "a_wrong_title.jpg")
            p.description 定解はこちら
          div
            p = @answer
          div
            span
              = @prev_quiz.quiz
              br
              = @prev_quiz.description
            = image_tag("01q.jpg")
          p style="text-align: right; font-size: 30px; "
            = link_to '次へ', quiz_path
          
      - else
        p = @quiz.level_text
        .quiz
          div
            = image_tag("q_title.jpg")
            .quiz-title
              p = @quiz.work
              p についての問題だよ！
          div
            span
              = @quiz.quiz
              br
              = @quiz.description
            = image_tag("01q.jpg")
          div
            - @quiz.options.each do |option|
              p
                = link_to "・#{option.value}", quiz_path(option_id: option.id)
    / p.privacy-text
    /   | サイト内素材の無断使用・転用は禁じます。
    /   br/
    /   | ©小島 功・エイケン　©光プロダクション・エイケン　©平井和正・桑田二郎／TBS　©TBS　©エイケン　©白土三平©エイケン　©長谷川町子美術館   ©横山隆一・エイケン　©田河水泡／講談社・エイケン　©佐藤さとる・村上勉／講談社・エイケン　©1976 雁屋哲・エイケン　©フジテレビ・エイケン　©ちばあきお・エイケン　©畑 正憲・エイケン　©美内すずえ／エイケン　©サトウサンペイ・フジテレビ・エイケン　©村上もとか／小学館・エイケン　©みつはしちかこ・エイケン　©アーネストTシートン・エイケン　©植田まさし／植田プロダクション・エイケン　©うえやまとち／講談社・エイケン　©布浦　翼／講談社・TBS・エイケン　©松竹・TBS・エイケン　©BSフジ・エイケン　©TBS・エイケン　©久里洋二・TBS・エイケン　©2005 ちばあきお・エイケン／プレイボール製作委員会　©光プロダクション・フジテレビ・エイケン　©いがらしみきお／竹書房・フジテレビ・エイケン

app/views/welcome/top.html.slim
div
  - unless @is_mobile
    .pc
      header
        .top-menu
          div
            = link_to image_tag("bt_home_pc.png"), root_path
          div
            = link_to image_tag("bt_01.png"), topic_url
          div
            = link_to image_tag("bt_02.png"), root_path
          div
            = link_to image_tag("bt_03.png"), quiz_url
          div
            = link_to image_tag("bt_04.png"), root_path
          div
            = link_to image_tag("bt_05.png"), root_path
        = link_to image_tag("uranai_pc.png"), root_path, class: 'urainai'
      article
        .topics
          = link_to image_tag("topix_title.png"), root_path
          div
            - @topics.each do |topic|
              div
                span = topic.date.strftime("%Y.%m.%d")
                = link_to topic.title, topic.link
        .chara
          = image_tag("chara.png")
        .banners
          = image_tag("banner01.png")
          = image_tag("banner01.png")
          = image_tag("banner01.png")
          = image_tag("banner01.png")
        p.privacy-text
          | サイト内素材の無断使用・転用は禁じます。
          br/
          | ©小島 功・エイケン　©光プロダクション・エイケン　©平井和正・桑田二郎／TBS　©TBS　©エイケン　©白土三平©エイケン　©長谷川町子美術館   ©横山隆一・エイケン　©田河水泡／講談社・エイケン　©佐藤さとる・村上勉／講談社・エイケン　©1976 雁屋哲・エイケン　©フジテレビ・エイケン　©ちばあきお・エイケン　©畑 正憲・エイケン　©美内すずえ／エイケン　©サトウサンペイ・フジテレビ・エイケン　©村上もとか／小学館・エイケン　©みつはしちかこ・エイケン　©アーネストTシートン・エイケン　©植田まさし／植田プロダクション・エイケン　©うえやまとち／講談社・エイケン　©布浦　翼／講談社・TBS・エイケン　©松竹・TBS・エイケン　©BSフジ・エイケン　©TBS・エイケン　©久里洋二・TBS・エイケン　©2005 ちばあきお・エイケン／プレイボール製作委員会　©光プロダクション・フジテレビ・エイケン　©いがらしみきお／竹書房・フジテレビ・エイケン
  - else
    .sp
      .header
        = link_to image_tag("bt_home.png"), root_path
        = link_to image_tag("bt_01.png"), topic_url
        = link_to image_tag("bt_02.png"), root_path
        = link_to image_tag("bt_03.png"), quiz_url
        = link_to image_tag("bt_04.png"), root_path
        = link_to image_tag("bt_05.png"), root_path
      div
        = image_tag("top_img_sp.png", style: "width: 100%;")
      .main
        .top-part
          div
            = image_tag("uranai.png")
          div
            = image_tag("chara.png")
        .top-part.title
          div
            = image_tag("navbar_01.png")
          div
            = image_tag("navbar_02.png")
        .top-part.title
          div
            = image_tag("navbar_03.png")
          div
            = image_tag("navbar_04.png")
        .list-header
          span トピックス
          span &gt;&gt;もっと見る
        .list
          .item
            div
              = image_tag("item.png")
            div
              p 2019.03.05
              p ブログタイトル
              p 本文引用本文引用本文引用本文引用本文引用本文引用本文引用本文引用本文引用本文引用本文引用本文引用本文引用本文引用本文引用本文引用本文引用本文引用本文引用本文引用本文引用本文引用本文引用本文引用
              span more
          .item
            div
              = image_tag("item.png")
            div
              p 2019.03.05
              p ブログタイトル
              p 本文引用本文引用本文引用本文引用本文引用本文引用本文引用本文引用本文引用本文引用本文引用本文引用本文引用本文引用本文引用本文引用本文引用本文引用本文引用本文引用本文引用本文引用本文引用本文引用
              span more
          .item
            div
              = image_tag("item.png")
            div
              p 2019.03.05
              p ブログタイトル
              p 本文引用本文引用本文引用本文引用本文引用本文引用本文引用本文引用本文引用本文引用本文引用本文引用本文引用本文引用本文引用本文引用本文引用本文引用本文引用本文引用本文引用本文引用本文引用本文引用
              span more
        .banners
          = image_tag("banner01.png")
          = image_tag("banner01.png")
        p.privacy-text
          | サイト内素材の無断使用・転用は禁じます。
          br/
          | ©小島 功・エイケン　©光プロダクション・エイケン　©平井和正・桑田二郎／TBS　©TBS　©エイケン　©白土三平©エイケン　©長谷川町子美術館   ©横山隆一・エイケン　©田河水泡／講談社・エイケン　©佐藤さとる・村上勉／講談社・エイケン　©1976 雁屋哲・エイケン　©フジテレビ・エイケン　©ちばあきお・エイケン　©畑 正憲・エイケン　©美内すずえ／エイケン　©サトウサンペイ・フジテレビ・エイケン　©村上もとか／小学館・エイケン　©みつはしちかこ・エイケン　©アーネストTシートン・エイケン　©植田まさし／植田プロダクション・エイケン　©うえやまとち／講談社・エイケン　©布浦　翼／講談社・TBS・エイケン　©松竹・TBS・エイケン　©BSフジ・エイケン　©TBS・エイケン　©久里洋二・TBS・エイケン　©2005 ちばあきお・エイケン／プレイボール製作委員会　©光プロダクション・フジテレビ・エイケン　©いがらしみきお／竹書房・フジテレビ・エイケン

app/views/welcome/topic.html.slim
div
  - unless @is_mobile
    .pc
      header
        .top-menu
          div
            = link_to image_tag("bt_home_pc.png"), root_path
          div
            = link_to image_tag("bt_01.png"), topic_url
          div
            = link_to image_tag("bt_02.png"), root_path
          div
            = link_to image_tag("bt_03.png"), quiz_url
          div
            = link_to image_tag("bt_04.png"), root_path
          div
            = link_to image_tag("bt_05.png"), root_path
        p.tag-name
          | トピックス
      article
        .list
          - @topics.each do |topic|
            .item
              = image_tag("item.png")
              div
                p = topic.date.strftime("%Y.%m.%d")
                p 
                 = link_to topic.title, topic.link
                p = topic.description
                span more
        p.privacy-text
          | サイト内素材の無断使用・転用は禁じます。
          br/
          | ©小島 功・エイケン　©光プロダクション・エイケン　©平井和正・桑田二郎／TBS　©TBS　©エイケン　©白土三平©エイケン　©長谷川町子美術館   ©横山隆一・エイケン　©田河水泡／講談社・エイケン　©佐藤さとる・村上勉／講談社・エイケン　©1976 雁屋哲・エイケン　©フジテレビ・エイケン　©ちばあきお・エイケン　©畑 正憲・エイケン　©美内すずえ／エイケン　©サトウサンペイ・フジテレビ・エイケン　©村上もとか／小学館・エイケン　©みつはしちかこ・エイケン　©アーネストTシートン・エイケン　©植田まさし／植田プロダクション・エイケン　©うえやまとち／講談社・エイケン　©布浦　翼／講談社・TBS・エイケン　©松竹・TBS・エイケン　©BSフジ・エイケン　©TBS・エイケン　©久里洋二・TBS・エイケン　©2005 ちばあきお・エイケン／プレイボール製作委員会　©光プロダクション・フジテレビ・エイケン　©いがらしみきお／竹書房・フジテレビ・エイケン
  - else
    .sp
      .header
        = link_to image_tag("bt_home.png"), root_path
        = link_to image_tag("bt_01.png"), topic_url
        = link_to image_tag("bt_02.png"), root_path
        = link_to image_tag("bt_03.png"), quiz_url
        = link_to image_tag("bt_04.png"), root_path
        = link_to image_tag("bt_05.png"), root_path
      .main
        p.list-title
          | トピックス
        .list
          .item
            div
              = image_tag("item.png")
            div
              p 2019.03.05
              p ブログタイトル
              p 本文引用本文引用本文引用本文引用本文引用本文引用本文引用本文引用本文引用本文引用本文引用本文引用本文引用本文引用本文引用本文引用本文引用本文引用本文引用本文引用本文引用本文引用本文引用本文引用
              span more
          .item
            div
              = image_tag("item.png")
            div
              p 2019.03.05
              p ブログタイトル
              p 本文引用本文引用本文引用本文引用本文引用本文引用本文引用本文引用本文引用本文引用本文引用本文引用本文引用本文引用本文引用本文引用本文引用本文引用本文引用本文引用本文引用本文引用本文引用本文引用
              span more
          .item
            div
              = image_tag("item.png")
            div
              p 2019.03.05
              p ブログタイトル
              p 本文引用本文引用本文引用本文引用本文引用本文引用本文引用本文引用本文引用本文引用本文引用本文引用本文引用本文引用本文引用本文引用本文引用本文引用本文引用本文引用本文引用本文引用本文引用本文引用
              span more
        p.privacy-text
          | サイト内素材の無断使用・転用は禁じます。
          br/
          | ©小島 功・エイケン　©光プロダクション・エイケン　©平井和正・桑田二郎／TBS　©TBS　©エイケン　©白土三平©エイケン　©長谷川町子美術館   ©横山隆一・エイケン　©田河水泡／講談社・エイケン　©佐藤さとる・村上勉／講談社・エイケン　©1976 雁屋哲・エイケン　©フジテレビ・エイケン　©ちばあきお・エイケン　©畑 正憲・エイケン　©美内すずえ／エイケン　©サトウサンペイ・フジテレビ・エイケン　©村上もとか／小学館・エイケン　©みつはしちかこ・エイケン　©アーネストTシートン・エイケン　©植田まさし／植田プロダクション・エイケン　©うえやまとち／講談社・エイケン　©布浦　翼／講談社・TBS・エイケン　©松竹・TBS・エイケン　©BSフジ・エイケン　©TBS・エイケン　©久里洋二・TBS・エイケン　©2005 ちばあきお・エイケン／プレイボール製作委員会　©光プロダクション・フジテレビ・エイケン　©いがらしみきお／竹書房・フジテレビ・エイケン